### PR TITLE
add to the landing page responsive css

### PR DESCRIPTION
**Pull request by AlaaEid-1**
relate #8

### CODE REVIEW

**Review by ahmedkhilla — DISMISSED** [review]

**Review by Rawan-ZA — DISMISSED** [review]

**Review by Rawan-ZA — APPROVED** [review]
styling need  to edit

**Review by sara219 — CHANGES_REQUESTED** [review]
something went wrong with about us section style

Screen Shot 2022-03-22 at 2 17 42 PM

**Comment by AlaaEid-1** [comment]
سارة هاد تعديلهم موجود بالrequest  الثاني

**Comment by AlaaEid-1** [comment]
@sara219  


التعديل ب  request  هاد add responsive css in about section in home page 
علشان responsive  كل وحدة ب issue حتلاقي التعديل ب  responsive about

**Review by sara219 — APPROVED** [review]

**Pull request merged**
